### ISSUE TITLE
la chat ionic deve tramite parametro recipient aprire direttamente la conversazione

### ISSUE THREAD

**Issue by andrealeo83** [chat21/chat21-ionic#38]
la chat ionic deve tramite parametro recipient aprire direttamente la conversazione come facevamo con openrecordz:

https://web.chat21.org/?recipient=support-group-L4MKx5dSWtbboG4I9zY

Ma sembra che non funzioni. puoi verificare?

**Comment by dariodepa** [comment]
aggiungere ?recipient= <id conversazione>
