### ISSUE TITLE
Ionic 4/5 support

### ISSUE THREAD

**Issue by ezequiel88** [chat21/chat21-ionic#58]
Is there a forecast for any version that is compatible with Ionic 4 or 5?

**Comment by andrealeo83** [comment]
yes it will be available next month.

**Comment by ezequiel88** [comment]
Thanks. beautiful work

**Comment by rajesh99** [comment]
Is there ionic4/5 client branch

**Comment by rajesh99** [comment]
Is there an ionic 4/5 client branch?

**Comment by rajesh99** [comment]
Is any branch was created for ioni 4/5
